name: Playwright Tests

on:
  push:
    branches:
      - '**'

env:
  PACKAGE_NAME: vanilla-routing

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Create Build
        run: npm run build

      - name: Run Playwright tests
        run: npm run test:ci
